---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest

dependencies:
  galaxy:
    collections:
      - { name: ansible.utils, version: 6.0.0 }
      - { name: community.vmware, version: 5.7.0 }
      - { name: vmware.vmware_rest, version: 4.7.0 }
      - { name: vmware.vmware, version: 2.1.0 }
  python:
    - aiohttp
#    - pyVmomi>=8.0.3.0.1
    - pyVmomi==8.0.3.0.1
    - vmware-vapi-common-client
    - vmware-vcenter

options:
  package_manager_path: /usr/bin/microdnf
